CREATE TABLE mytable(
   Room_ID       INTEGER  NOT NULL PRIMARY KEY 
  ,Hotel_ID      INTEGER  NOT NULL
  ,Hotel_Name    VARCHAR(26) NOT NULL
  ,Address       VARCHAR(105) NOT NULL
  ,Room_Number   INTEGER  NOT NULL
  ,City          VARCHAR(11) NOT NULL
  ,Tariff        NUMERIC(6,1) NOT NULL
  ,Max_Occupants INTEGER  NOT NULL
  ,City_View     INTEGER  NOT NULL
  ,Comp_BF       INTEGER  NOT NULL
  ,WiFi          INTEGER  NOT NULL
  ,Car_Rental    INTEGER  NOT NULL
  ,AC            INTEGER  NOT NULL
);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (1,1,'Taj Intercontinental','B-35/1, Race Course Road, South Bombay, Memapur',101,'Mumbai',32300,3,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (2,1,'Taj Intercontinental','B-35/1, Race Course Road, South Bombay, Memapur',103,'Mumbai',12000,3,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (3,1,'Taj Intercontinental','B-35/1, Race Course Road, South Bombay, Memapur',332,'Mumbai',9500,3,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (4,1,'Taj Intercontinental','B-35/1, Race Course Road, South Bombay, Memapur',201,'Mumbai',9500,3,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (5,1,'Taj Intercontinental','B-35/1, Race Course Road, South Bombay, Memapur',401,'Mumbai',9500,3,1,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (6,2,'Hotel Bhimas','High Court Road, Nyay Marg, Townie Central, Navi Mumbai',124,'Mumbai',8700,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (7,2,'Hotel Bhimas','High Court Road, Nyay Marg, Townie Central, Navi Mumbai',332,'Mumbai',9990,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (8,2,'Hotel Bhimas','High Court Road, Nyay Marg, Townie Central, Navi Mumbai',445,'Mumbai',8700,3,1,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (9,2,'Hotel Bhimas','High Court Road, Nyay Marg, Townie Central, Navi Mumbai',101,'Mumbai',8700,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (10,2,'Hotel Bhimas','High Court Road, Nyay Marg, Townie Central, Navi Mumbai',201,'Mumbai',8700,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (11,2,'Hotel Bhimas','High Court Road, Nyay Marg, Townie Central, Navi Mumbai',202,'Mumbai',8700,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (12,3,'Brigade Metropolis Plus','Gulab Estate, T2 Terminal International Airport, MTNL Road, Sakinaka, Andheri, Mumbai, Maharashtra 400072',101,'Mumbai',10249,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (13,3,'Brigade Metropolis Plus','Gulab Estate, T2 Terminal International Airport, MTNL Road, Sakinaka, Andheri',110,'Mumbai',10250,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (14,3,'Brigade Metropolis Plus','Gulab Estate, T2 Terminal International Airport, MTNL Road, Sakinaka, Andheri, Mumbai, Maharashtra 400074',332,'Mumbai',10251,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (15,4,'Oyo Manikantha 5166','Gulab Estate, 8B, Sakinaka Tele Exchange Lane, T2 Airport Road, Sakinaka',101,'Mumbai',3400,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (16,4,'Oyo Manikantha 5167','Gulab Estate, 8B, Sakinaka Tele Exchange Lane, T2 Airport Road, Sakinaka',102,'Mumbai',3400,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (17,4,'Oyo Manikantha 5168','Gulab Estate, 8B, Sakinaka Tele Exchange Lane, T2 Airport Road, Sakinaka',103,'Mumbai',3400,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (18,4,'Oyo Manikantha 5169','Gulab Estate, 8B, Sakinaka Tele Exchange Lane, T2 Airport Road, Sakinaka',104,'Mumbai',3400,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (19,4,'Oyo Manikantha 5170','Gulab Estate, 8B, Sakinaka Tele Exchange Lane, T2 Airport Road, Sakinaka',105,'Mumbai',3400,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (20,4,'Oyo Manikantha 5171','Gulab Estate, 8B, Sakinaka Tele Exchange Lane, T2 Airport Road, Sakinaka',332,'Mumbai',3400,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (21,4,'Oyo Manikantha 5172','Gulab Estate, 8B, Sakinaka Tele Exchange Lane, T2 Airport Road, Sakinaka',445,'Mumbai',3400,2,1,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (22,5,'Hotel Grandeur','Crystal Plaza Plot N0.18/27, Sector 7 Kharghar, Navi Mumbai',202,'Mumbai',4500,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (23,5,'Hotel Grandeur','Crystal Plaza Plot N0.18/27, Sector 7 Kharghar, Navi Mumbai',204,'Mumbai',4500,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (24,5,'Hotel Grandeur','Crystal Plaza Plot N0.18/27, Sector 7 Kharghar, Navi Mumbai',311,'Mumbai',4500,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (25,5,'Hotel Grandeur','Crystal Plaza Plot N0.18/27, Sector 7 Kharghar, Navi Mumbai',332,'Mumbai',4500,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (26,5,'Hotel Grandeur','Crystal Plaza Plot N0.18/27, Sector 7 Kharghar, Navi Mumbai',607,'Mumbai',4500,2,1,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (27,6,'Hotel Sitara','VM-123/4, Gandhi Road, opposite BSNL Bhawan, Kotagummam',332,'Rajahmundry',1250,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (28,6,'Hotel Sitara','VM-123/4, Gandhi Road, opposite BSNL Bhawan, Kotagummam',333,'Rajahmundry',1700,3,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (29,6,'Hotel Sitara','VM-123/4, Gandhi Road, opposite BSNL Bhawan, Kotagummam',335,'Rajahmundry',1250,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (30,6,'Hotel Sitara','VM-123/4, Gandhi Road, opposite BSNL Bhawan, Kotagummam',101,'Rajahmundry',1250,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (31,6,'Hotel Sitara','VM-123/4, Gandhi Road, opposite BSNL Bhawan, Kotagummam',105,'Rajahmundry',1250,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (32,6,'Hotel Sitara','VM-123/4, Gandhi Road, opposite BSNL Bhawan, Kotagummam',109,'Rajahmundry',1270,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (33,6,'Hotel Sitara','VM-123/4, Gandhi Road, opposite BSNL Bhawan, Kotagummam',111,'Rajahmundry',1300,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (34,7,'Geetha Apsara Residemcy','Danavaipeta, opposite Anand Regancy Theatre',205,'Rajahmundry',940,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (35,7,'Geetha Apsara Residemcy','Danavaipeta, opposite Anand Regancy Theatre',209,'Rajahmundry',940,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (36,7,'Geetha Apsara Residemcy','Danavaipeta, opposite Anand Regancy Theatre',102,'Rajahmundry',1300,3,0,0,1,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (37,7,'Geetha Apsara Residemcy','Danavaipeta, opposite Anand Regancy Theatre',332,'Rajahmundry',940,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (38,7,'Geetha Apsara Residemcy','Danavaipeta, opposite Anand Regancy Theatre',104,'Rajahmundry',940,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (39,7,'Geetha Apsara Residemcy','Danavaipeta, opposite Anand Regancy Theatre',203,'Rajahmundry',940,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (40,7,'Geetha Apsara Residemcy','Danavaipeta, opposite Anand Regancy Theatre',301,'Rajahmundry',940,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (41,8,'Shelton Grand','26-3-7, Jampet, NAD Road',301,'Rajahmundry',2400,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (42,8,'Shelton Grand','27-3-7, Jampet, NAD Road',307,'Rajahmundry',2400,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (43,8,'Shelton Grand','28-3-7, Jampet, NAD Road',332,'Rajahmundry',3040,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (44,8,'Shelton Grand','29-3-7, Jampet, NAD Road',407,'Rajahmundry',2550,2,1,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (45,8,'Shelton Grand','30-3-7, Jampet, NAD Road',502,'Rajahmundry',2400,2,1,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (46,8,'Shelton Grand','31-3-7, Jampet, NAD Road',504,'Rajahmundry',2350,2,1,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (47,8,'Shelton Grand','32-3-7, Jampet, NAD Road',511,'Rajahmundry',2400,2,1,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (48,9,'Udipi Akshaya','NH-162, Bobbaralanka Nagar, near Kadiyam',201,'Rajahmundry',1300,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (49,9,'Udipi Akshaya','NH-162, Bobbaralanka Nagar, near Kadiyam',203,'Rajahmundry',1300,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (50,9,'Udipi Akshaya','NH-162, Bobbaralanka Nagar, near Kadiyam',332,'Rajahmundry',1450,3,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (51,9,'Udipi Akshaya','NH-162, Bobbaralanka Nagar, near Kadiyam',301,'Rajahmundry',1300,2,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (52,9,'Udipi Akshaya','NH-162, Bobbaralanka Nagar, near Kadiyam',401,'Rajahmundry',1300,2,1,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (53,10,'Satya Homestay','Maisamma Chaurassa Circle, Near Satyam Brewing Agencies, NTPL Road',101,'Rajahmundry',450,1,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (54,10,'Satya Homestay','Maisamma Chaurassa Circle, Near Satyam Brewing Agencies, NTPL Road',104,'Rajahmundry',450,1,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (55,10,'Satya Homestay','Maisamma Chaurassa Circle, Near Satyam Brewing Agencies, NTPL Road',332,'Rajahmundry',450,1,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (56,10,'Satya Homestay','Maisamma Chaurassa Circle, Near Satyam Brewing Agencies, NTPL Road',201,'Rajahmundry',450,1,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (57,11,'La Hospin','101-A/2, Raj Marg, New Delhi Capital Area (UT)',101,'Delhi',3400,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (58,11,'La Hospin','102-A/2, Raj Marg, New Delhi Capital Area (UT)',103,'Delhi',3400,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (59,11,'La Hospin','103-A/2, Raj Marg, New Delhi Capital Area (UT)',332,'Delhi',3400,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (60,12,'Rafale Grand','Door NM-101, Scamabad, Bharath Vihar Nagar, Gandhinagar',106,'Delhi',8500,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (61,12,'Rafale Grand','Door NM-101, Scamabad, Bharath Vihar Nagar, Gandhinagar',204,'Delhi',8500,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (62,12,'Rafale Grand','Door NM-101, Scamabad, Bharath Vihar Nagar, Gandhinagar',303,'Delhi',8500,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (63,12,'Rafale Grand','Door NM-101, Scamabad, Bharath Vihar Nagar, Gandhinagar',332,'Delhi',8500,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (64,13,'Tempe Residency','Wahi Bagh, Banega Nagar, Gurgaon-Delhi Religious Highway',101,'Delhi',19250,4,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (65,13,'Tempe Residency','Wahi Bagh, Banega Nagar, Gurgaon-Delhi Religious Highway',202,'Delhi',19250,4,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (66,13,'Tempe Residency','Wahi Bagh, Banega Nagar, Gurgaon-Delhi Religious Highway',303,'Delhi',19250,4,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (67,13,'Tempe Residency','Wahi Bagh, Banega Nagar, Gurgaon-Delhi Religious Highway',332,'Delhi',19250,4,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (68,14,'Oyo 2020','Vision Metropolis Complex, near AIIMS Delhi, Birla Nagar',301,'Delhi',16020,4,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (69,14,'Oyo 2020','Vision Metropolis Complex, near AIIMS Delhi, Birla Nagar',202,'Delhi',15345,4,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (70,14,'Oyo 2020','Vision Metropolis Complex, near AIIMS Delhi, Birla Nagar',202,'Delhi',15250,4,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (71,14,'Oyo 2020','Vision Metropolis Complex, near AIIMS Delhi, Birla Nagar',221,'Delhi',15900,4,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (72,14,'Oyo 2020','Vision Metropolis Complex, near AIIMS Delhi, Birla Nagar',332,'Delhi',15260,4,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (73,15,'Hotel Unity','G-101/A, Gandhi Road, MG Nagar',101,'Vadodara',3300,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (74,15,'Hotel Unity','G-101/A, Gandhi Road, MG Nagar',202,'Vadodara',3300,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (75,15,'Hotel Unity','G-101/A, Gandhi Road, MG Nagar',104,'Vadodara',3300,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (76,15,'Hotel Unity','G-101/A, Gandhi Road, MG Nagar',105,'Vadodara',3300,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (77,15,'Hotel Unity','G-101/A, Gandhi Road, MG Nagar',332,'Vadodara',3300,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (78,16,'Democles Grand','7, Jetalpur Rd, Sampatrao Colony, Alkapuri',102,'Vadodara',2100,2,0,0,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (79,16,'Democles Grand','7, Jetalpur Rd, Sampatrao Colony, Alkapuri',104,'Vadodara',2100,2,0,0,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (80,16,'Democles Grand','7, Jetalpur Rd, Sampatrao Colony, Alkapuri',201,'Vadodara',2100,2,0,0,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (81,16,'Democles Grand','7, Jetalpur Rd, Sampatrao Colony, Alkapuri',303,'Vadodara',2050,2,0,0,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (82,16,'Democles Grand','7, Jetalpur Rd, Sampatrao Colony, Alkapuri',401,'Vadodara',2100,2,1,0,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (83,17,'Geass Residencies','Layout 54-3/A, Sardar Vallabhai Nagar, Iron Man Road',101,'Vadodara',2300,3,0,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (84,17,'Geass Residencies','Layout 54-3/A, Sardar Vallabhai Nagar, Iron Man Road',103,'Vadodara',1070,2,0,0,1,0,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (85,17,'Geass Residencies','Layout 54-3/A, Sardar Vallabhai Nagar, Iron Man Road',105,'Vadodara',1340,2,0,0,1,0,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (86,17,'Geass Residencies','Layout 54-3/A, Sardar Vallabhai Nagar, Iron Man Road',107,'Vadodara',1070,2,0,0,1,0,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (87,17,'Geass Residencies','Layout 54-3/A, Sardar Vallabhai Nagar, Iron Man Road',209,'Vadodara',980,2,0,0,0,0,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (88,17,'Geass Residencies','Layout 54-3/A, Sardar Vallabhai Nagar, Iron Man Road',332,'Hyderabad',1070,2,0,0,1,0,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (89,18,'Yagami Heights','Comicon Road, Gacchibowli Area, opposite Light Avenue',506,'Hyderabad',1400,3,1,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (90,18,'Yagami Heights','Comicon Road, Gacchibowli Area, opposite Light Avenue',708,'Hyderabad',990,2,1,0,0,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (91,18,'Yagami Heights','Comicon Road, Gacchibowli Area, opposite Light Avenue',802,'Hyderabad',990,2,1,0,0,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (92,18,'Yagami Heights','Comicon Road, Gacchibowli Area, opposite Light Avenue',332,'Hyderabad',975,2,0,0,0,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (93,18,'Yagami Heights','Comicon Road, Gacchibowli Area, opposite Light Avenue',401,'Hyderabad',1050,2,1,0,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (94,19,'Valmiki Bhawan, BPHC','Shameerpet (de)Forested Area, near Jawaharnagar, Thumukunta',332,'Hyderabad',130,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (95,19,'Valmiki Bhawan, BPHC','Shameerpet (de)Forested Area, near Jawaharnagar, Thumukunta',330,'Hyderabad',170,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (96,19,'Valmiki Bhawan, BPHC','Shameerpet (de)Forested Area, near Jawaharnagar, Thumukunta',101,'Hyderabad',145,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (97,19,'Valmiki Bhawan, BPHC','Shameerpet (de)Forested Area, near Jawaharnagar, Thumukunta',220,'Hyderabad',99,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (98,20,'Alankrita Holistic Resorts','Middle of nowhere, Thumukunta, CRPF Highway – 500078',101,'Hyderabad',5600,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (99,20,'Alankrita Holistic Resorts','Middle of nowhere, Thumukunta, CRPF Highway – 500078',104,'Hyderabad',5840,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (100,21,'Capital O Metropolis','A90, Manikantha Marg, near SC Railway Station',102,'Hyderabad',5800,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (101,21,'Capital O Metropolis','A90, Manikantha Marg, near SC Railway Station',101,'Hyderabad',6100,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (102,21,'Capital O Metropolis','A90, Manikantha Marg, near SC Railway Station',332,'Hyderabad',6050,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (103,22,'Nestlay Cafa','New No. 6, Old No. 9, Plot No. 7, Zerald Garden, Second Lane, Casa Major Road, Egmore',110,'Chennai',4890,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (104,22,'Nestlay Cafa','New No. 6, Old No. 9, Plot No. 7, Zerald Garden, Second Lane, Casa Major Road, Egmore',202,'Chennai',4990,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (105,22,'Nestlay Cafa','New No. 6, Old No. 9, Plot No. 7, Zerald Garden, Second Lane, Casa Major Road, Egmore',332,'Chennai',5040,2,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (106,23,'Regentra Central','36, Royapettah High Rd, Jagadambal colony, Sripuram, Teachers Colony, Royapettah',332,'Chennai',7090,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (107,23,'Regentra Central','37, Royapettah High Rd, Jagadambal colony, Sripuram, Teachers Colony, Royapettah',303,'Chennai',6500,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (108,23,'Regentra Central','38, Royapettah High Rd, Jagadambal colony, Sripuram, Teachers Colony, Royapettah',401,'Chennai',6980,2,1,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (109,24,'Ulli Residency','Rama Pillai Street,Jawaharlal nehru Stadium, Periyamet',403,'Chennai',7100,2,1,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (110,24,'Ulli Residency','Rama Pillai Street,Jawaharlal nehru Stadium, Periyamet',404,'Chennai',7300,2,1,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (111,24,'Ulli Residency','Rama Pillai Street,Jawaharlal nehru Stadium, Periyamet',332,'Chennai',7050,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (112,25,'The Belstead','103, Nungambakkam High Rd, Ponnangipuram, Nungambakkam',332,'Chennai',10670,3,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (113,25,'The Belstead','103, Nungambakkam High Rd, Ponnangipuram, Nungambakkam',301,'Chennai',13425,3,0,1,1,1,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (114,26,'Tushar Bhawan','Namma Highway, Namma Nagar, near NLS Bangalore',202,'Bangalore',9850.5,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (115,26,'Tushar Bhawan','Namma Highway, Namma Nagar, near NLS Bangalore',103,'Bangalore',9870,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (116,26,'Tushar Bhawan','Namma Highway, Namma Nagar, near NLS Bangalore',332,'Bangalore',10250,3,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (117,27,'Kantha Brigade','near National Institute of Design, Miyapur, Thumakuru',201,'Bangalore',3020,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (118,27,'Kantha Brigade','near National Institute of Design, Miyapur, Thumakuru',204,'Bangalore',3100,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (119,27,'Kantha Brigade','near National Institute of Design, Miyapur, Thumakuru',332,'Bangalore',2990,2,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (120,28,'Balharsha Bhawan','opposite Lalbagh entrance, MGR Road, Bengaluru',506,'Bangalore',560,2,1,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (121,28,'Balharsha Bhawan','opposite Lalbagh entrance, MGR Road, Bengaluru',410,'Bangalore',590,2,1,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (122,28,'Balharsha Bhawan','opposite Lalbagh entrance, MGR Road, Bengaluru',332,'Bangalore',720,2,0,0,0,1,0);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (123,29,'Leela Palace','23, HAL Old Airport Rd, HAL 2nd Stage, Kodihalli',332,'Bangalore',32300,5,0,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (124,29,'Leela Palace','23, HAL Old Airport Rd, HAL 2nd Stage, Kodihalli',403,'Bangalore',16900,3,1,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (125,29,'Leela Palace','23, HAL Old Airport Rd, HAL 2nd Stage, Kodihalli',709,'Bangalore',7800,2,1,1,1,0,1);
INSERT INTO mytable(Room_ID,Hotel_ID,Hotel_Name,Address,Room_Number,City,Tariff,Max_Occupants,City_View,Comp_BF,WiFi,Car_Rental,AC) VALUES (126,29,'Leela Palace','23, HAL Old Airport Rd, HAL 2nd Stage, Kodihalli',906,'Bangalore',4570,2,1,1,1,0,1);
RENAME TABLE mytable TO room_info;