/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import static app.Utilities.checkAvailability;
import static app.DBConnection.getResult;
import static app.Login.finalusername;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static  java.awt.Image.SCALE_SMOOTH;
/**
 *
 * @author rohit
 */
public class BookingConfirmation extends javax.swing.JFrame {
//            Wifi_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(WiFi)).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
    int HID, tariff, number_of_rooms, rooms_to_book = 1;
    Date checkIn, checkOut;
    String hotel_name, Address, Description, City;
    String image;
    String WiFi, Car_Rental, AC, Swimming_Pool, Comp_BF;
    static String yes = "/home/rohit/Desktop/Hotel-Booking-App/App/media/Yes.png";
    static String no = "/home/rohit/Desktop/Hotel-Booking-App/App/media/No.png";
    BookingConfirmation(int HID, String Hotel, String Address, String City, int tariff, Date inDate, Date outDate) {
        this.HID = HID;
        this.checkIn = inDate;
        this.checkOut = outDate;
        this.tariff = tariff;
        this.hotel_name = Hotel;
        this.Address = Address;
        this.City = City;
        image = "/home/rohit/Desktop/Hotel-Booking-App/App/media/";
        if(HID%3 == 0){
            Description = "Located in close proximity of the Airport and Bus Stand,  " + Hotel + " offers you premium rooms at extremely affordable rates. ";
            Description += "Book your room today, and leave your stay on us!\n";
            Description += "Address: ";
            Description += Address;
            image += "0.jpg";
        }
        else if(HID%3 == 1){
            Description = "There was an idea. An idea called the H Initiative.";
            Description +="The idea was to bring together a group of remarkable people, see if they could become something more.";
            Description +="See if they could all work together and provide the best of hospitality. So that you worry about having fun.";
            Description +="While we look after everything else\n\n";
            Description +=Address;
            image += "1.jpg";
        }
        else{
            Description = "Home away from home.";
            Description += "We believe that your stay should be as comfortable as your home. And we deliver.";
            Description += "With personalised 24/7 service that is unparallelled elsewhere";
            Description += ("\nAddress: " + Address);
            image += "2.jpg";
        }
        ResultSet rs = getResult("SELECT WiFi, Car_Rental, AC, Swimming_Pool, Comp_BF, Number_of_rooms FROM room_info WHERE Hotel_ID = " + HID + ";");
        try{
            rs.next();
            this.number_of_rooms = rs.getInt("Number_of_rooms");
            if(rs.getInt("WiFi") == 1){
                WiFi = yes;
            }
            else{
                WiFi = no;
            }
            if(rs.getInt("Comp_BF") == 1){
                Comp_BF = yes;
            }
            else{
                Comp_BF = no;
            }
            if(rs.getInt("Swimming_Pool") == 1)
                Swimming_Pool = yes;
            else
                Swimming_Pool = no;
            if(rs.getInt("Car_Rental") == 1)
                Car_Rental = yes;
            else
                Car_Rental = no;
            if(rs.getInt("AC") == 1){
                AC = yes;
            }
            else
                AC = no;
        }catch(SQLException e){
            e.printStackTrace();
        }
        initComponents();               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Image = new javax.swing.JLabel();
        HotelName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetailsAboutHotel = new javax.swing.JTextArea();
        NumberOfGuests = new javax.swing.JSlider(1,number_of_rooms*3,1);
        ConfirmButton = new javax.swing.JButton();
        WiFiLabel = new javax.swing.JLabel();
        Comp_BFLabel = new javax.swing.JLabel();
        CarRentalLabel = new javax.swing.JLabel();
        SwimmingPoolLabel = new javax.swing.JLabel();
        ACLabel = new javax.swing.JLabel();
        CompBF_img = new javax.swing.JLabel();
        Wifi_img = new javax.swing.JLabel();
        Pool_img = new javax.swing.JLabel();
        AC_img = new javax.swing.JLabel();
        CarRental_img = new javax.swing.JLabel();
        AmenitiesLabel = new javax.swing.JLabel();
        GuestsLabel = new javax.swing.JLabel();
        GuestsNumberDisclaimer = new javax.swing.JLabel();
        TnC = new javax.swing.JLabel();
        NumberOfRoomsLabel = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        IDType = new javax.swing.JComboBox<>();
        EnterIDNumLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CheckOutDateLabel = new javax.swing.JLabel();
        RoomsAvailableInHotel = new javax.swing.JLabel();
        CheckInDateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Image.setIcon(new javax.swing.ImageIcon(image));
        Image.setText("Image");

        HotelName.setFont(new java.awt.Font("Noto Sans Mono CJK TC Regular", 1, 18)); // NOI18N
        HotelName.setText(hotel_name +", " + City);
        HotelName.setToolTipText("");

        DetailsAboutHotel.setEditable(false);
        DetailsAboutHotel.setBackground(new java.awt.Color(242, 241, 240));
        DetailsAboutHotel.setColumns(20);
        DetailsAboutHotel.setLineWrap(true);
        DetailsAboutHotel.setRows(5);
        DetailsAboutHotel.setText(Description);
        DetailsAboutHotel.setToolTipText("");
        DetailsAboutHotel.setAutoscrolls(false);
        DetailsAboutHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(DetailsAboutHotel);

        NumberOfGuests.setMajorTickSpacing(1);
        NumberOfGuests.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NumberOfGuestsStateChanged(evt);
            }
        });

        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        WiFiLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        WiFiLabel.setText("WiFi");

        Comp_BFLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Comp_BFLabel.setText("Complimentary BF");

        CarRentalLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        CarRentalLabel.setText("Car Rental");

        SwimmingPoolLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        SwimmingPoolLabel.setText("Swimming Pool");

        ACLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        ACLabel.setText("AC");

        CompBF_img.setIcon(new javax.swing.ImageIcon(Comp_BF));

        Wifi_img.setIcon(new javax.swing.ImageIcon(WiFi));

        Pool_img.setIcon(new javax.swing.ImageIcon(Swimming_Pool));

        AC_img.setIcon(new javax.swing.ImageIcon(AC));

        CarRental_img.setIcon(new javax.swing.ImageIcon(Car_Rental));

        AmenitiesLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        AmenitiesLabel.setText("Amenities");

        GuestsLabel.setText("Number of Guests: " + NumberOfGuests.getValue());

        GuestsNumberDisclaimer.setText("* Three guests maximum per room");

        TnC.setText("By pressing confirm you agree to the Terms and Conditions.");

        NumberOfRoomsLabel.setText("Number of Rooms*: " + rooms_to_book);

        username.setText("Username: "+ finalusername);

        IDType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aadhar Card", "Drivers Lisence", "Passport", "Voter ID Card", "Student ID Card" }));
        IDType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IDTypeItemStateChanged(evt);
            }
        });
        IDType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTypeActionPerformed(evt);
            }
        });

        EnterIDNumLabel.setText("Enter " + IDType.getSelectedItem() + " number:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        CheckOutDateLabel.setText("Check-out: " + checkOut);

        RoomsAvailableInHotel.setText("Rooms available: " + checkAvailability(HID, checkIn, checkOut));

        CheckInDateLabel.setText("Check in: " + checkIn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(Pool_img, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SwimmingPoolLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Wifi_img, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(WiFiLabel)
                                                .addGap(48, 48, 48)
                                                .addComponent(AC_img, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ACLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(CarRental_img, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CarRentalLabel))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(HotelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(AmenitiesLabel))))
                    .addComponent(GuestsNumberDisclaimer)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(ConfirmButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CompBF_img, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(GuestsLabel))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(NumberOfGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(178, 178, 178)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(NumberOfRoomsLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(EnterIDNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(IDType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Comp_BFLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CheckInDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(CheckOutDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RoomsAvailableInHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TnC)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(HotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AmenitiesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AC_img, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Wifi_img, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(WiFiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pool_img, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ACLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CarRental_img, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(CarRentalLabel)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(SwimmingPoolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CompBF_img, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(Comp_BFLabel))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuestsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumberOfGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(NumberOfRoomsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GuestsNumberDisclaimer)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(username)
                                .addGap(12, 12, 12)
                                .addComponent(IDType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EnterIDNumLabel)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(CheckInDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckOutDateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(RoomsAvailableInHotel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TnC)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void NumberOfGuestsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NumberOfGuestsStateChanged
        int n = NumberOfGuests.getValue();
        GuestsLabel.setText("Number of guests: " + n);
        if(n%3 == 0){
            rooms_to_book = n/3;
        }
        else{
            rooms_to_book = (n/3) + 1;
        }
        NumberOfRoomsLabel.setText("Number of Rooms*: " + rooms_to_book);        
    }//GEN-LAST:event_NumberOfGuestsStateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void IDTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IDTypeItemStateChanged
        EnterIDNumLabel.setText("Enter " + IDType.getSelectedItem() + " number:");
    }//GEN-LAST:event_IDTypeItemStateChanged

    private void IDTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACLabel;
    private javax.swing.JLabel AC_img;
    private javax.swing.JLabel AmenitiesLabel;
    private javax.swing.JLabel CarRentalLabel;
    private javax.swing.JLabel CarRental_img;
    private javax.swing.JLabel CheckInDateLabel;
    private javax.swing.JLabel CheckOutDateLabel;
    private javax.swing.JLabel CompBF_img;
    private javax.swing.JLabel Comp_BFLabel;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JTextArea DetailsAboutHotel;
    private javax.swing.JLabel EnterIDNumLabel;
    private javax.swing.JLabel GuestsLabel;
    private javax.swing.JLabel GuestsNumberDisclaimer;
    private javax.swing.JLabel HotelName;
    private javax.swing.JComboBox<String> IDType;
    private javax.swing.JLabel Image;
    private javax.swing.JSlider NumberOfGuests;
    private javax.swing.JLabel NumberOfRoomsLabel;
    private javax.swing.JLabel Pool_img;
    private javax.swing.JLabel RoomsAvailableInHotel;
    private javax.swing.JLabel SwimmingPoolLabel;
    private javax.swing.JLabel TnC;
    private javax.swing.JLabel WiFiLabel;
    private javax.swing.JLabel Wifi_img;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
